name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  deliverit:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build Docker image and push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
          image: ahmedelmeligy/ahmed
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.REPO_USERNAME }}"
          password: "${{ secrets.REPO_PASSWORD }}"
          tags: latest  

